### ISSUE TITLE
Add `ln` and `exp` (and generic versions)

### ISSUE THREAD

**Issue by PgBiel** [xddxdd/nix-math#1]
Hello,
First of all, thanks for the great library. It seems to be truly one of a kind in the Nix ecosystem; the options for math functions in the Nix ecosystem are currently very limited...

Do you think the library could have support for more exponential-related functions with float support, such as `exp` and `ln`, maybe generic `pow` and `log` as well?

I've seen some reference implementations around such as https://github.com/nadavrot/fast_log that we could try to adapt. I'm no expert on the subject though :)

Thanks in advance!

**Comment by xddxdd** [comment]
Hi, nice to hear there are someone else who is enjoying this library!

I have added `exp`, `ln`, `pow` and `log` functions. Please try them out and let me know how they work.

**Comment by PgBiel** [comment]
Woah!!! That was fast!

I've given it a quick spin locally, and I think that should do it from what I've seen so far! I'll let you know if I face any issues, but for now it's looking good!

Thanks for the quick response! :slightly_smiling_face:

**Comment by PgBiel** [comment]
By the way @xddxdd, was it intentional that you called the generic log version `ln`, and the base `e` log as `log`? I think you may have accidentally swapped the names, as `ln` is commonly used for base `e` specifically :p

**Comment by xddxdd** [comment]
I was using `log` because numpy uses `log` as the base `e` logarithmetic function. But your point makes sense, I have swapped the `log` and `ln` functions.

**Comment by PgBiel** [comment]
Ah, fair enough. Thanks again! 🙂
